### ISSUE TITLE
Can't run this code

### ISSUE THREAD

**Issue by mikutown** [Thinklab-SJTU/PPO-BiHyb#2]
请问该代码必须在装有Nvidia显卡的linux服务器上才能运行吗？我在自己的Mac上安装了不包含cuda的torch等包，运行dag_ppo_bihyb_train.py代码报错:
Traceback (most recent call last):
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_train.py", line 461, in <module>
    main(parse_arguments())
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_train.py", line 267, in main
    ppo = PPO(dag_graph, args, device)
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_train.py", line 139, in __init__
    self.policy = ActorCritic(*ac_params).to(self.device)
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_train.py", line 100, in __init__
    self.state_encoder = GraphEncoder(node_feature_dim, node_output_size, batch_norm, one_hot_degree, gnn_layers)
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_model.py", line 28, in __init__
    batch_norm=self.batch_norm)
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/pyg_graph_models.py", line 68, in __init__
    self.init_parameters()
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/pyg_graph_models.py", line 72, in init_parameters
    nn.init.xavier_uniform_(getattr(self, 'conv_{}'.format(l)).weight)
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'GCNConv' object has no attribute 'weight'
<img width="1114" alt="Screen Shot 2022-09-14 at 15 21 43" src="https://user-images.githubusercontent.com/35498600/190087865-d2a24538-ff40-417b-be9f-00e44d23ce19.png">

**Comment by mikutown** [comment]
my pip list is:
Package                 Version
----------------------- -----------
absl-py                 1.2.0
cachetools              5.2.0
certifi                 2022.6.15
charset-normalizer      2.1.1
click                   8.1.3
Cython                  0.29.32
decorator               5.1.1
Deprecated              1.2.13
google-auth             2.11.0
google-auth-oauthlib    0.4.6
grpcio                  1.48.1
idna                    3.4
importlib-metadata      4.12.0
Jinja2                  3.1.2
joblib                  1.1.0
Markdown                3.4.1
MarkupSafe              2.1.1
networkx                2.2
numpy                   1.21.6
oauthlib                3.2.1
ortools                 9.4.1874
Pillow                  9.2.0
pip                     22.1.2
protobuf                3.19.5
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyparsing               3.0.9
PyYAML                  6.0
requests                2.28.1
requests-oauthlib       1.3.1
rsa                     4.9
scikit-learn            1.0.2
scipy                   1.7.3
setuptools              63.4.1
six                     1.16.0
tabulate                0.8.10
tensorboard             2.10.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
texttable               1.6.4
threadpoolctl           3.1.0
torch                   1.7.1
torch-cluster           1.5.8
torch-geometric         2.1.0.post1
torch-scatter           2.0.5
torch-sparse            0.6.8
torch-spline-conv       1.2.0
torchaudio              0.7.2
torchvision             0.8.2
tqdm                    4.64.1
tsplib95                0.7.1
typing_extensions       4.3.0
urllib3                 1.26.12
Werkzeug                2.2.2
wheel                   0.37.1
wrapt                   1.14.1
zipp                    3.8.1

**Comment by mikutown** [comment]
如果代码只能在含有Nvidia显卡的服务器上运行，请回复我一下 谢谢你QWQ

**Comment by rogerwwww** [comment]
Hi there,

代码应该可以在无GPU的机器上运行。你遇到的问题可能是torch-geometric的版本太新了（似乎pyg作者没有考虑向后兼容），我已经更新了README，请参照README上所列的版本重新安装试试

This seems not an issue related to GPU. Probably it is because your torch-geometric version is too new (seems that the pyg team may have broken some backward compatibility). I have updated the README with the versions that I used, and please try reinstalling these python packages.

**Comment by mikutown** [comment]
好像可以运行了，但是运行时系统提醒需要安装tensorflow(Warning: Tensorboard not loading, please install tensorflow to enable...)，装了1.13.1版本tensorflow后又报错
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 702, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/type_checkers.py", line 264, in CheckValue
    raise TypeError(message)
TypeError: tensor(1.2860) has type <class 'torch.Tensor'>, but expected one of: numbers.Real

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 717, in setter
    field_setter(self, new_value)
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 705, in field_setter
    'Cannot set %s to %.1024r: %s' % (field.full_name, new_value, e))
TypeError: Cannot set tensorflow.Summary.Value.simple_value to tensor(1.2860): tensor(1.2860) has type <class 'torch.Tensor'>, but expected one of: numbers.Real

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_train.py", line 461, in <module>
    main(parse_arguments())
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_train.py", line 324, in main
    summary_writer.add_scalar('critic mse/train', closs, timestep)
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/tfboard_helper.py", line 39, in add_scalar
    summary = tf.Summary(value=[tf.Summary.Value(tag=name, simple_value=value)])
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 560, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 477, in _ReraiseTypeErrorWithFieldName
    raise exc.with_traceback(sys.exc_info()[2])
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 717, in setter
    field_setter(self, new_value)
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 705, in field_setter
    'Cannot set %s to %.1024r: %s' % (field.full_name, new_value, e))
TypeError: Cannot set tensorflow.Summary.Value.simple_value to tensor(1.2860): tensor(1.2860) has type <class 'torch.Tensor'>, but expected one of: numbers.Real for field Value.simple_value
```

**Comment by mikutown** [comment]
<img width="1235" alt="Screen Shot 2022-09-14 at 17 13 33" src="https://user-images.githubusercontent.com/35498600/190113246-755ea6dc-9afe-4fbf-8bc8-9d3b6198f9b7.png">
是不是tensorboard的版本不太对啊 😭

**Comment by rogerwwww** [comment]
建议先不装tensorboard，训练测试部分能运行即可。tensorboard属于锦上添花

**Comment by rogerwwww** [comment]
Here are the tensorflow/tensorboard versions in my environment:

```
tensorboard             1.14.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow              1.14.0
tensorflow-estimator    1.14.0
```

**Comment by mikutown** [comment]
非常非常非常非常非常非常非常感谢！能力有限 我就先不装tensorboard了哈哈哈哈哈

**Comment by mikutown** [comment]
你好！我已经收到了你的邮件，我会尽快给你回复！Hello!I have received your e-mail,I will reply you soon!
