### ISSUE TITLE
关于dag_ppo_bihyb_train.py的运行问题

### ISSUE THREAD

**Issue by mikutown** [Thinklab-SJTU/PPO-BiHyb#5]
你好大神，我运行了dag_ppo_bihyb_train.py后，系统提示
```
########## Evaluate on Test ##########
BEAMSEARCH 	gid 0 	time 77.97 	reward 0.4729 	ratio 0.2949 	ours 1.1304 	gap -0.0441 	sfs 1.6033 	cp 1.1803 	ts 1.3701 	action [(7, 24), (1, 24), (3, 24), (25, 24), (29, 24), (30, 15), (33, 24), (32, 24), (9, 24), (40, 24), (16, 15), (4, 24), (17, 15), (3, 49), (7, 49), (32, 15), (3, 41), (3, 34), (3, 23), (3, 33), (3, 40), (3, 35), (3, 4), (3, 20), (3, 18), (3, 28), (3, 21)] 	prob (0.021, 0.024),(0.020, 0.021),(0.020, 0.025),(0.020, 0.023),(0.020, 0.024),(0.020, 0.024),(0.020, 0.024),(0.020, 0.027),(0.020, 0.023),(0.020, 0.024),(0.020, 0.023),(0.020, 0.024),(0.020, 0.023),(0.020, 0.026),(0.020, 0.025),(0.020, 0.027),(0.020, 0.026),(0.020, 0.030),(0.020, 0.035),(0.020, 0.036),(0.020, 0.037),(0.020, 0.039),(0.020, 0.040),(0.020, 0.042),(0.020, 0.046),(0.020, 0.048),(0.020, 0.059)
Traceback (most recent call last):
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_train.py", line 461, in <module>
    main(parse_arguments())
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_train.py", line 379, in main
    test_dict = evaluate(ppo.policy, dag_graph, tuples_test, args.max_timesteps, args.search_size, mp_pool)
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_eval.py", line 135, in evaluate
    bs_result = beam_search(policy_net, dag_graph, inp_graph, ori_greedy, max_steps, search_size, mp_pool)
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_eval.py", line 70, in beam_search
    state_feat = state_encoder(graph_list)
  File "/opt/anaconda3/envs/ppob/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/dag_ppo_bihyb_model.py", line 39, in forward
    batched_graphs = construct_graph_batch(input_graphs, self.one_hot_degree, self.device)
  File "/Users/yunsenye/Documents/projects/python/PPO-BiHyb/utils.py", line 17, in construct_graph_batch
    elif isinstance(graphs, list) and isinstance(graphs[0], nx.DiGraph):
IndexError: list index out of range
```
请问一下这大概是什么问题导致Evaluate on Test 过程无法正常进行

**Comment by mikutown** [comment]
<img width="1267" alt="Screen Shot 2022-09-16 at 14 36 31" src="https://user-images.githubusercontent.com/35498600/190572590-6f29cf11-500d-4427-83d6-3a07a50ca1a7.png">

**Comment by rogerwwww** [comment]
Did you modify anything? It works with no error on my side.
